apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-private-pvc
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  accessModes:
    {{- with .Values.persistentVolumes.appPrivateAccessModes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  resources:
    requests:
      storage: {{ default "10Gi" .Values.persistentVolumes.appPrivateCapacity }}
  storageClassName: {{ default "local-storage" .Values.storageClass.name }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-app-private-pv