apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nginx-pv
  labels:
    name: {{ .Release.Name }}-nginx-pv
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  capacity:
    storage: {{ default "10Gi" .Values.persistentVolumes.nginxCapacity }}
  accessModes:
    {{- with .Values.persistentVolumes.nginxAccessModes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  persistentVolumeReclaimPolicy: {{ default "Retain" .Values.storageClass.reclaimPolicy }}
  storageClassName: {{ default "local-storage" .Values.storageClass.name }}
  hostPath:
    path: {{ default "/orocommerce/app" .Values.persistentVolumes.nginxHostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.persistentVolumes.nodeHostname }}