apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: {{ .Release.Name }}-nginx
  selector:
    app: {{ .Release.Name }}-nginx