apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP