apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-websocket
  labels:
    app: {{ .Release.Name }}-websocket
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-websocket
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
