database:
  defaultContainerName: database
  defaultLivenessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - exec pg_isready -U orodbuser -d orodb
    failureThreshold: 6
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  defaultReadinessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - -e
        - |
          exec pg_isready -U orodbuser -d orodb
    failureThreshold: 6
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  defaultContainerResource:
    requests:
      memory: '500Mi'
      cpu: '500m'
    limits:
      memory: '1000Mi'
      cpu: '1000m'
