apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ default "orocommerce" .Values.secretName }}
type: Opaque
data:
  ORO_DB_HOST: "{{- printf "%s-postgre" .Release.Name | b64enc -}}"
  ORO_DB_PORT: NTQzMg==
  ORO_DB_NAME: b3JvZGI=
  ORO_DB_USER: b3JvZGJ1c2Vy
  ORO_DB_PASSWORD: b3JvZGJwYXNz

  ORO_USER_RUNTIME: d3d3LWRhdGE=
  ORO_ENV: cHJvZA==
  ORO_USER_NAME: YWRtaW4=
  ORO_USER_PASSWORD: YWRtaW4=
  ORO_USER_FIRSTNAME: Sm9obg==
  ORO_USER_LASTNAME: RG9l
  ORO_USER_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
  ORO_SAMPLE_DATA: eQ==
  ORO_ORGANIZATION_NAME: T1JP
  ORO_FORMATTING_CODE: ZnJfRlI=
  ORO_APP_PROTOCOL: {{ default "https" .Values.secrets.protocol | b64enc }}
  ORO_APP_DOMAIN: b3JvLmRlbW8=
  ORO_WEB_HOST: b3JvY29tbWVyY2Utbmdpbng=
  ORO_NGINX_HTTP_PORT: ODA=
  ORO_NGINX_HTTPS_PORT: ODA=
  ORO_INSTALL_OPTIONS: ""
  ORO_MULTIHOST_OPERATION_FOLDER: L3Zhci93d3cvb3JvL3Zhci9tdWx0aWhvc3Q=
  ORO_MAINTENANCE_LOCK_FOLDER: L3Zhci93d3cvb3JvL3Zhci9tYWludGVuYW5jZQ==
  ORO_MAINTENANCE_LOCK_FILE_NAME: bWFpbnRlbmFuY2VfbG9jaw==
  ORO_MAINTENANCE_LOCK_FILE_PATH: L3Zhci93d3cvb3JvL3Zhci9tYWludGVuYW5jZS9tYWludGVuYW5jZV9sb2Nr
  ORO_PHP_FPM_HOST: "{{- printf "%s-app" .Release.Name | b64enc -}}"
  ORO_PHP_FPM_PORT: OTAwMA==
  ORO_CONSUMER_SERVICE: Y29uc3VtZXI=
  ORO_PAUSE_SERVICES: cGhwLWZwbS1hcHB8Y3Jvbg==
  ORO_RESTART_SERVICES: cGhwLWZwbS1hcHB8Y3Jvbnx3cw==
  ORO_DEBUGGER: LW5v
  ORO_DB_VERSION: MTcuMg==
  ORO_PG_VER: MTcuMi1hbHBpbmU=

  ORO_DB_DSN: "{{- printf "postgres://orodbuser:orodbpass@%s-postgre:5432/orodb?sslmode=disable&charset=utf8&serverVersion=17.2" .Release.Name | b64enc -}}"
  ORO_DB_ROOT_USER: b3JvZGJ1c2Vy
  ORO_DB_ROOT_PASSWORD: b3JvZGJwYXNz

  ORO_MQ_DSN: ZGJhbDo=
  ORO_SESSION_DSN: bmF0aXZlOg==
  ORO_SEARCH_ENGINE_DSN: b3JtOj9wcmVmaXg9b3JvX3NlYXJjaA==
  ORO_WEBSITE_SEARCH_ENGINE_DSN: b3JtOj9wcmVmaXg9b3JvX3dlYnNpdGVfc2VhcmNo
  ORO_MAILER_DSN: c210cDovL21haWw6MTAyNQ==
  ORO_WEBSOCKET_BACKEND_HOST: "{{- printf "%s-websocket" .Release.Name | b64enc -}}"
  ORO_WEBSOCKET_BACKEND_PORT: ODA4MA==
  ORO_WEBSOCKET_SERVER_DSN: Ly8wLjAuMC4wOjgwODA=
  ORO_WEBSOCKET_FRONTEND_DSN: Ly8qOjgwL3dz
  ORO_WEBSOCKET_BACKEND_DSN: "{{- printf "tcp://%s-websocket:8080" .Release.Name | b64enc -}}"

  ORO_LANGUAGE: ZnJfRlI=
  ORO_LANGUAGE_SUFFIX: LWZy
  ORO_APP_COUNTRY: RlI=
  ORO_APP_TIMEZONE: RXVyb3BlL1Bhcmlz
  ORO_APP_TEMPERATURE_UNIT: Y2Vsc2l1cw==
  ORO_APP_WIND_SPEED_UNIT: bWV0ZXJzX3Blcl9zZWNvbmQ=
  ORO_APP_CURRENCY: RVVS

  ORO_APP_URL: "{{- printf "%s://oro.demo" (default "https" .Values.secrets.protocol) | b64enc -}}"
  ORO_SITES: eyJvcm8uZGVtbyI6eyJkb21haW5fZGlyZWN0IjpmYWxzZSwibG9jYXRpb25zX21lcmdlIjp0cnVlfX0=
  ORO_GLOBAL_HTTP_PORT: ODA=
  ORO_GLOBAL_SHARED_ROOT_DIR: L3Zhci93d3cvb3JvL3Zhci9tYWludGVuYW5jZQ==
  ORO_GLOBAL_LOCK_FILE_PATH: L3Zhci93d3cvb3JvL3Zhci9tYWludGVuYW5jZS9nbG9iYWxfbG9jaw==
  ORO_GLOBAL_USE_UPSTREAM: dHJ1ZQ==
  ORO_GLOBAL_LIMIT_REQ_ENABLE: ZmFsc2U=
  ORO_GLOBAL_TESTCOOKIE_ENABLE: ZmFsc2U=

  ORO_HTTP_UPSTREAM: "{{- printf "{\"app\":{\"servers\":[{\"host\":\"%s-app\",\"port\": 9000}]},\"ws\":{\"servers\":[{\"host\":\"%s-websocket\",\"port\": 8080}]}}" .Release.Name .Release.Name | b64enc -}}"
  
  ORO_SERVER_LOCATION: "{{- printf "{\"~ /index\\.php(/|$)\": {\"type\":\"php\",\"fastcgi_param\": {\"HTTPS\": \"%s\"}}, \"@rewrite\": {\"type\": \"named\", \"raw_prepend\": [\"if (-f /var/www/oro/var/maintenance/global_lock) { add_header \\\"Cache-Control\\\" \\\"no-cache\\\"; return 503; }\"]}}" (ternary "on" "off" (eq .Values.secrets.protocol "https")) | b64enc -}}"

  HP_MEMORY_LIMIT: NjA5Nk0=