apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-app-hpa
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-app
  minReplicas: {{ default 1 .Values.app.hpaMinReplicase }}
  maxReplicas: {{ default 1 .Values.app.hpaMaxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ default 20 .Values.app.hpaAverageCpuUtilization }}