apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-cron
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app-cron
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app-cron
    spec:
      securityContext:
        {{- with .Values.rootSecurityContext }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      initContainers:
        - name: {{ default "verify-connection" .Values.cron.initContainerName }}
          image: {{ .Values.images.orocomerceImageInit }}:{{ .Values.images.orocomerceImageInitTag }}
          command:
            - "sh"
            - "-c"
            - "until nc -z {{ .Release.Name }}-app 9000; do echo \"Waiting for php-fpm connection...\"; sleep 1; done"
      containers:
        - name: {{ default "verify-connection" .Values.cron.defaultContainerName }}
          image: {{ .Values.images.orocomerceImageBaseRuntime }}:{{ .Values.images.orocomerceImageBaseRuntimeTag }}
          args:
            - "cron"
          env:
            - name: ORO_LOG_PATH
              value: php://stderr
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            {{- with .Values.cron.defaultContainerResource }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-app-pvc
              mountPath: /var/www/oro
            - name: {{ .Release.Name }}-app-cache-pvc
              mountPath: /var/www/oro/var/cache
            - name: {{ .Release.Name }}-app-multihost-operation-pvc
              mountPath: /var/www/oro/var/multihost
            - name: {{ .Release.Name }}-app-maintenance-pvc
              mountPath: /var/www/oro/var/maintenance
            - name: {{ .Release.Name }}-app-public-pvc
              mountPath: /var/www/oro/public/media
            - name: {{ .Release.Name }}-app-private-pvc
              mountPath: /var/www/oro/var/data
      volumes:
        - name: {{ .Release.Name }}-app-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-cache-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-cache-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-multihost-operation-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-multihost-operation-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-maintenance-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-maintenance-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-public-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-public-pvc
            readOnly: false
        - name: {{ .Release.Name }}-app-private-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-app-private-pvc
            readOnly: false
