apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: {{ .Release.Name }}-database
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  ports:
  - port: 5432
    name: database
    targetPort: 5432
  selector:
    app: {{ .Release.Name }}-database
