apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgre
  labels:
    app: {{ .Release.Name }}-postgre
  namespace: {{ default "orocommerce" .Values.namespace }}
spec:
  ports:
  - port: 5432
    name: postgre
    targetPort: 5432
  selector:
    app: {{ .Release.Name }}-postgre